Repository boostcamp-2020/Project12-A-Slack-Web, pull requests merged in 2020-11, with the labels that each got.

#7 Feature/be/swagger (#6)
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/swagger/openapi.yaml
  server/src/swagger/paths/_index.yaml
  server/tsconfig.json
Labels: Review needed

#11 Feat/googlelogin
  client/tsconfig.json
  server/@types/user.d.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controller/index.ts
  server/src/controller/user/index.ts
  server/src/controller/user/user.ts
  server/src/controller/workspace/index.ts
  server/src/middleware/verifyUser.ts
  server/src/model/channel.ts
  server/src/model/file.ts
  server/src/model/index.ts
  server/src/model/message.ts
  server/src/model/reaction.ts
  server/src/model/section.ts
  server/src/model/sequelize.ts
  server/src/model/thread.ts
  server/src/model/user.ts
  server/src/model/userChannelSection.ts
  server/src/model/workspace.ts
  server/src/service/user/index.ts
  server/src/service/workspace/index.ts
  server/src/util/jwt.ts
  server/src/util/passportConfig.ts
  server/tsconfig.json
Labels: BE, 기능추가

#13 Feature/be/error handling example (#12)
  server/src/app.ts
  server/src/controller/index.ts
  server/src/controller/thread/index.ts
  server/src/controller/thread/thread.controller.ts
  server/src/service/thread.service.ts
  server/src/swagger/openapi.yaml
  server/src/swagger/paths/_index.yaml
  server/src/swagger/paths/thread.yaml
  server/src/util/constant.ts
Labels: Review needed

#58 Refactor/fe/eslint config
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  server/src/app.ts
  server/src/service/thread.service.ts
Labels: Review needed

#60 Feature/fe/image component
  client/src/App.tsx
  client/src/component/atom/Image.tsx
  client/tsconfig.json
  server/src/app.ts
Labels: Review needed

#59 feat : atom button example
  client/src/component/atom/Button.tsx
  client/src/component/atom/index.tsx
Labels: FE, 기능추가

#61 Feat/fe/loginpage
  client/src/App.tsx
  client/src/component/atom/Button.tsx
  client/src/component/atom/index.ts
  client/src/constant/color.ts
Labels: FE, 기능추가

#62 Feature/fe/text-component
  client/src/component/atom/Text.tsx
Labels: Review needed

#64 feat: mocule buttonDiv example
  client/src/App.tsx
  client/src/component/atom/Button.tsx
  client/src/component/atom/Text.tsx
  client/src/component/atom/index.ts
  client/src/component/molecule/ButtonDiv.tsx
  client/src/component/molecule/index.ts
  client/tsconfig.json
Labels: 기능수정, 기능추가

#63 Feature/fe/header (#15)
  client/src/component/atom/MyIcon.tsx
  client/src/component/molecule/Header.tsx
Labels: FE

#67 feat: modify Button atom, ButtonDiv molecule
  client/src/App.tsx
  client/src/component/atom/Button.tsx
  client/src/component/molecule/ButtonDiv.tsx
Labels: Review needed

#69 Refactor/be/path alias
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/service/thread.service.ts
  server/src/service/user.service.ts
  server/tsconfig.json
Labels: Review needed

#73 Refactor : button.style.ts 분리 + jwt token 연장 + BE alias
  client/src/App.tsx
  client/src/component/atom/Button/Button.style.ts
  client/src/component/atom/Button/Button.tsx
  client/src/component/molecule/ButtonDiv.tsx
  server/src/app.ts
  server/src/util/jwt.ts
  server/src/util/passport-config.ts
Labels: BE, FE, 기능수정

#74 Feature/fe/storybook-config (#71)
  client/.storybook/main.js
  client/package-lock.json
  client/package.json
  client/src/component/atom/Button/Button.stories.tsx
  client/src/component/atom/Button/Button.style.ts
  client/src/component/atom/Button/Button.tsx
  client/src/component/atom/Button/index.ts
Labels: Review needed

#76 feature/fe/header-input (#15, #16)
  client/src/component/atom/Icon.tsx
  client/src/component/molecule/HeaderInput.tsx
  client/src/component/organism/Header.tsx
  client/src/component/organism/index.ts
Labels: FE, Review needed, 코드개선

#75 feat: google login logic
  client/src/App.tsx
  client/src/page/User/LoginPage.tsx
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/util/myAxios.ts
  server/src/controller/user/index.ts
  server/src/controller/user/user.controller.ts
  server/src/middleware/user.middleware.ts
  server/src/util/passport-config.ts
Labels: BE, FE, 기능수정, 기능추가

#77 Feature/fe/action bar - add Modal molecule, refactor Button atom (#66)
  client/src/component/atom/Button/Button.tsx
  client/src/component/atom/Button/index.ts
  client/src/component/atom/ModalWrapper.tsx
  client/src/component/atom/Overlay.tsx
  client/src/component/atom/index.ts
  client/src/component/molecule/Modal.tsx
  client/src/component/molecule/index.ts
Labels: Review needed

#78 fix: Button atom
  client/src/component/atom/Button/Button.stories.tsx
  client/src/component/atom/Button/Button.style.ts
  client/src/component/atom/Button/Button.tsx
Labels: Review needed

#80 Feature/fe/thread component (#19)
  client/src/component/atom/Image.tsx
  client/src/component/organism/MessageCard/MessageCard.stories.tsx
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/MessageCard/index.ts
  client/src/component/organism/index.ts
  client/src/constant/color.ts
Labels: Review needed

#85 Feature/fe/routing
  client/src/App.tsx
  client/webpack.config.js
Labels: Review needed

#82 Feat/fe/loginpage
  client/src/util/myAxios.ts
  client/tsconfig.json
  server/.eslintrc.json
  server/src/app.ts
  server/src/controller/thread/thread.controller.ts
  server/src/controller/user/user.controller.ts
  server/src/service/user.service.ts
Labels: Review needed

#84 feature/fix icon import problem
  client/src/component/atom/Icon/Icon.tsx
  client/src/component/atom/Icon/index.ts
Labels: FE, Review needed, 버그수정

#83 Feat/be/workspace api
  client/src/App.tsx
  client/src/page/Workspace/WorkspacJoinPage.tsx
  server/src/controller/workspace/index.ts
  server/src/controller/workspace/workspace.controller.ts
  server/src/model/user.model.ts
  server/src/model/workspace.model.ts
  server/src/service/message.service.ts
  server/src/service/workspace.service.ts
  server/tsconfig.json
Labels: Review needed

#86 Feature/fe/text component - refactor
  client/src/component/atom/Text.tsx
  client/src/component/atom/Text/Text.style.ts
  client/src/component/atom/Text/Text.tsx
  client/src/component/atom/Text/index.tsx
  client/src/component/molecule/ButtonDiv.tsx
Labels: Review needed

#90 fix: remove dependency
  server/src/model/channel.model.ts
  server/src/model/file.model.ts
  server/src/model/index.ts
  server/src/model/message.model.ts
  server/src/model/reaction.model.ts
  server/src/model/section.model.ts
  server/src/model/thread.model.ts
  server/src/model/user.model.ts
  server/src/model/userChannelSection.ts
  server/src/model/workspace.model.ts
Labels: Review needed

#91 Refactor/style
  client/src/component/atom/Button/Button.stories.tsx
  client/src/component/atom/Button/Button.style.ts
  client/src/component/atom/Button/Button.tsx
  client/src/component/atom/Button/index.ts
  client/src/component/atom/Image/Image.stories.tsx
  client/src/component/atom/Image/Image.tsx
  client/src/component/atom/Image/index.ts
  client/src/component/molecule/Modal.tsx
  client/src/component/molecule/ReplyButton/ReplyButton.style.ts
  client/src/component/molecule/ReplyButton/ReplyButton.tsx
  client/src/component/molecule/ReplyButton/index.ts
Labels: Review needed

#96 Feature/fe/input atom (#93)
  client/src/component/atom/Input/Input.stories.tsx
  client/src/component/atom/Input/Input.tsx
  client/src/component/atom/Input/index.ts
Labels: Review needed

#97 Refactor/fe/component structure
  client/src/component/molecule/ButtonDiv.tsx
  client/src/component/molecule/ButtonDiv/ButtonDiv.stories.tsx
  client/src/component/molecule/ButtonDiv/ButtonDiv.tsx
  client/src/component/molecule/ButtonDiv/index.ts
  client/src/component/molecule/Modal/Modal.stories.tsx
  client/src/component/molecule/Modal/Modal.tsx
  client/src/component/molecule/Modal/index.ts
  client/src/component/molecule/ReplyButton/ReplyButton.stories.tsx
Labels: Review needed

#100 Feature/fe/action bar (#29, #56, #57)
  client/package-lock.json
  client/package.json
  client/src/component/atom/Button/Button.tsx
  client/src/component/atom/Button/index.ts
  client/src/component/atom/Text/Text.stories.tsx
  client/src/component/atom/Text/Text.tsx
  client/src/component/atom/Text/index.tsx
  client/src/component/molecule/ActionMenuButton/ActionMenuButton.stories.tsx
  client/src/component/molecule/ActionMenuButton/ActionMenuButton.style.ts
  client/src/component/molecule/ActionMenuButton/ActionMenuButton.tsx
  client/src/component/molecule/ActionMenuButton/index.ts
  client/src/component/molecule/index.ts
  client/src/component/organism/ActionBar/ActionBar.stories.tsx
  client/src/component/organism/ActionBar/ActionBar.style.ts
  client/src/component/organism/ActionBar/ActionBar.tsx
  client/src/component/organism/ActionBar/index.ts
  client/src/component/organism/MessageActionsMenu/MessageActionsMenu.stories.tsx
  client/src/component/organism/MessageActionsMenu/MessageActionsMenu.tsx
  client/src/component/organism/MessageActionsMenu/index.ts
  client/src/component/organism/ReactionPicker/ReactionPicker.stories.tsx
  client/src/component/organism/ReactionPicker/ReactionPicker.tsx
  client/src/component/organism/ReactionPicker/index.ts
  client/src/component/organism/index.ts
  client/src/constant/color.ts
  client/src/constant/icon.ts
Labels: Review needed

#99 Feature/fe/message editor (#92)
  client/package-lock.json
  client/package.json
  client/src/component/organism/MessageEditor/MessageEditor.stories.tsx
  client/src/component/organism/MessageEditor/MessageEditor.style.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/component/organism/MessageEditor/index.ts
  client/src/component/organism/index.ts
Labels: Review needed, help wanted

#101 Feature/fe/header/popup (#20)
  client/src/component/atom/Button/Button.tsx
  client/src/component/atom/Button/index.ts
  client/src/component/molecule/ButtonDiv/ButtonDiv.tsx
  client/src/component/molecule/ButtonDiv/index.ts
  client/src/component/molecule/HeaderInput/HeaderInput.style.ts
  client/src/component/molecule/HeaderInput/HeaderInput.tsx
  client/src/component/molecule/Modal/Modal.tsx
  client/src/component/organism/Header/Header.tsx
  client/src/constant/color.ts
  client/src/constant/icon.ts
Labels: FE

#104 Fix/toast import
  client/package-lock.json
  client/package.json
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/webpack.config.js
Labels: Review needed

#110 Feature/fe/channel header
  client/src/component/atom/ModalWrapper/ModalWrapper.tsx
  client/src/component/atom/ModalWrapper/index.ts
  client/src/component/atom/Text/Text.tsx
  client/src/component/organism/Avatar/Avatar.stories.tsx
  client/src/component/organism/Avatar/Avatar.style.ts
  client/src/component/organism/Avatar/Avatar.tsx
  client/src/component/organism/Avatar/index.ts
  client/src/component/organism/ChannelHeader/ChannelHeader.stories.tsx
  client/src/component/organism/ChannelHeader/ChannelHeader.style.ts
  client/src/component/organism/ChannelHeader/ChannelHeader.tsx
  client/src/component/organism/ChannelHeader/index.ts
  client/src/component/organism/UserProfileModal/UserProfileModal.stories.tsx
  client/src/component/organism/UserProfileModal/UserProfileModal.style.ts
  client/src/component/organism/UserProfileModal/UserProfileModal.tsx
  client/src/component/organism/UserProfileModal/index.ts
  client/src/component/organism/index.ts
  client/src/constant/icon.ts
Labels: Review needed

#107 refactor/fe/header
  client/src/component/atom/Icon/Icon.tsx
  client/src/component/atom/Icon/index.ts
  client/src/component/organism/Header/Header.style.ts
  client/src/component/organism/Header/Header.tsx
  client/src/component/organism/Header/index.ts
  client/src/constant/icon.ts
Labels: Review needed, 코드개선

#106 Fix/be/apis
  server/src/controller/file/file.controller.ts
  server/src/controller/index.ts
  server/src/controller/message/message.controller.ts
  server/src/controller/reaction/index.ts
  server/src/controller/reaction/reaction.controller.ts
  server/src/controller/thread/thread.controller.ts
  server/src/controller/user/index.ts
  server/src/service/channel.service.ts
  server/src/service/file.service.ts
  server/src/service/message.service.ts
  server/src/service/reaction.service.ts
  server/src/service/thread.service.ts
Labels: Review needed

#112 Feautre/fe/combine message card
  client/.eslintrc.json
  client/.storybook/main.js
  client/src/component/atom/Icon/Icon.tsx
  client/src/component/molecule/ReplyButton/ReplyButton.tsx
  client/src/component/molecule/index.ts
  client/src/component/organism/ActionBar/ActionBar.style.ts
  client/src/component/organism/MessageCard/MessageCard.stories.tsx
  client/src/component/organism/MessageCard/MessageCard.style.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/index.ts
  client/src/constant/color.ts
  client/src/constant/icon.ts
  client/src/util/date.ts
Labels: Review needed

#114 Refactor/fe/message card (#17, #92)
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/component/atom/Input/Input.tsx
  client/src/component/atom/Input/index.ts
  client/src/component/atom/index.ts
  client/src/component/organism/MessageEditor/MessageEditor.style.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/constant/color.ts
  client/src/constant/icon.ts
  client/webpack.config.js
Labels: Review needed

#115 Refactor/be/swagger
  server/src/controller/user/user.controller.ts
  server/src/controller/workspace/workspace.controller.ts
  server/src/service/workspace.service.ts
  server/src/swagger/openapi.yaml
  server/src/swagger/paths/channel-info.yaml
  server/src/swagger/paths/channel-join.yaml
  server/src/swagger/paths/channel.yaml
  server/src/swagger/paths/file.yaml
  server/src/swagger/paths/message.yaml
  server/src/swagger/paths/reaction.yaml
  server/src/swagger/paths/thread.yaml
  server/src/swagger/paths/user.yaml
  server/src/swagger/paths/workspace-join.yaml
  server/src/swagger/paths/workspace-userlist.yaml
  server/src/swagger/paths/workspace.yaml
Labels: Review needed

#119 feature/fe/sidebar (#20, #25, #27, #30, #33, #40)
  client/src/App.tsx
  client/src/component/atom/Icon/Icon.tsx
  client/src/component/atom/Icon/index.ts
  client/src/component/molecule/Section/Section.style.ts
  client/src/component/molecule/Section/Section.tsx
  client/src/component/molecule/Section/index.ts
  client/src/component/molecule/index.ts
  client/src/component/organism/SideBar/SideBar.style.ts
  client/src/component/organism/SideBar/SideBar.tsx
  client/src/component/organism/SideBar/index.ts
  client/src/component/organism/index.ts
  client/src/constant/color.ts
  client/src/constant/icon.ts
Labels: FE

#131 Refactor/fe/unify component declare
  client/src/component/atom/Image/Image.tsx
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/component/organism/ReactionPicker/ReactionPicker.tsx
Labels: Review needed

#132 Feature/fe/channel browser
  client/src/App.tsx
  client/src/component/molecule/HeaderInput/HeaderInput.style.ts
  client/src/component/molecule/HeaderInput/HeaderInput.tsx
  client/src/component/organism/ChannelCard/ChannelCard.stories.tsx
  client/src/component/organism/ChannelCard/ChannelCard.style.ts
  client/src/component/organism/ChannelCard/ChannelCard.tsx
  client/src/component/organism/ChannelCard/index.ts
  client/src/component/organism/Header/Header.style.ts
  client/src/component/organism/SideBar/SideBar.style.ts
  client/src/constant/icon.ts
  client/src/page/Channel/ChannelBrowserPage.tsx
Labels: Review needed
