Repository boostcamp-2020/Project12-A-Slack-Web, pull requests merged in 2020-12, with the labels that each got.

#134 Feature/fe/channel browser
  client/src/App.tsx
  client/src/component/atom/Icon/Icon.tsx
  client/src/component/molecule/CloseButton/CloseButton.tsx
  client/src/component/molecule/CloseButton/index.ts
  client/src/component/molecule/ReplyButton/ReplyButton.style.ts
  client/src/component/molecule/ReplyButton/ReplyButton.tsx
  client/src/component/molecule/index.ts
  client/src/component/organism/ActionBar/ActionBar.tsx
  client/src/component/organism/ChannelBrowserHeader/ChannelBrowserHeader.style.ts
  client/src/component/organism/ChannelBrowserHeader/ChannelBrowserHeader.tsx
  client/src/component/organism/ChannelBrowserHeader/index.ts
  client/src/component/organism/ChannelHeader/ChannelHeader.style.ts
  client/src/component/organism/ChannelHeader/ChannelHeader.tsx
  client/src/component/organism/ChannelList/ChannelList.style.ts
  client/src/component/organism/ChannelList/ChannelList.tsx
  client/src/component/organism/ChannelList/index.ts
  client/src/component/organism/MessageCard/MessageCard.stories.tsx
  client/src/component/organism/MessageCard/MessageCard.style.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/ThreadList/ThreadList.style.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/component/organism/ThreadList/index.ts
  client/src/component/organism/index.ts
  client/src/page/Channel/ChannelBrowserPage.tsx
  client/src/page/Channel/ChannelPage.tsx
  client/src/page/Channel/data.ts
  server/src/service/channel.service.ts
Labels: Review needed

#139 Feature/fe/thread list + ThreadDetail
  client/src/component/organism/ChannelHeader/ChannelHeader.style.ts
  client/src/component/organism/ChannelHeader/ChannelHeader.tsx
  client/src/component/organism/MemberListModal/MemberListModal.tsx
  client/src/component/organism/MessageCard/MessageCard.stories.tsx
  client/src/component/organism/MessageCard/MessageCard.style.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/ThreadDetail/ThreadDetail.style.ts
  client/src/component/organism/ThreadDetail/ThreadDetail.tsx
  client/src/component/organism/ThreadDetail/index.ts
  client/src/component/organism/ThreadList/ThreadList.style.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/component/organism/index.ts
  client/src/page/Channel/ChannelPage.tsx
  client/src/page/Channel/data.ts
Labels: Review needed

#138 Feature/fe/redux (#137)
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/thread.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/store/index.ts
  client/src/store/thread.ts
  client/tsconfig.json
  client/webpack.config.js
  server/package-lock.json
  server/package.json
Labels: Review needed

#140 Feat/fe/redux
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/user.ts
  client/src/api/workspace.ts
  client/src/component/atom/Input/Input.tsx
  client/src/component/atom/Input/index.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/hoc/Auth.tsx
  client/src/index.tsx
  client/src/page/User/LoginPage.tsx
  client/src/page/Workspace/NewWorkspacePage.tsx
  client/src/page/Workspace/WorkspacJoinPage.tsx
  client/src/page/Workspace/WorkspaceJoinPage.tsx
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/page/index.ts
  client/src/store/index.ts
  client/src/store/thread.store.ts
  client/src/store/workspace.store.ts
  client/src/util/myAxios.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: Review needed

#142 Feature/fe/reaction
  client/package-lock.json
  client/package.json
  client/src/component/atom/Button/Button.tsx
  client/src/component/atom/Button/index.ts
  client/src/component/molecule/ReactionButton/ReactionButton.stories.tsx
  client/src/component/molecule/ReactionButton/ReactionButton.tsx
  client/src/component/molecule/ReactionButton/index.ts
  client/src/component/molecule/index.ts
  client/src/component/organism/MessageCard/MessageCard.stories.tsx
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/ReactionList/ReactionList.stories.tsx
  client/src/component/organism/ReactionList/ReactionList.style.ts
  client/src/component/organism/ReactionList/ReactionList.tsx
  client/src/component/organism/ReactionList/index.ts
  client/src/component/organism/ReactionPicker/ReactionPicker.stories.tsx
  client/src/component/organism/ReactionPicker/ReactionPicker.tsx
  client/src/component/organism/index.ts
  client/src/constant/color.ts
Labels: Review needed

#144 Feature/fe/redux async (#143)
  client/src/api/thread.ts
  client/src/api/workspace.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/page/Channel/ChannelPage.tsx
  client/src/page/Workspace/NewWorkspacePage.tsx
  client/src/page/Workspace/WorkspaceJoinPage.tsx
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/store/index.ts
  client/src/store/reducer/index.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/reducer/workspace.reducer.ts
  client/src/store/saga/index.ts
  client/src/store/saga/thread.saga.ts
Labels: Review needed

#145 Feature/socket
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/page/Channel/ChannelPage.tsx
  client/src/socket.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/thread.saga.ts
  server/src/app.ts
  server/src/service/thread.service.ts
  server/src/socket.ts
  server/src/swagger/paths/thread.yaml
Labels: Review needed

#146 Feature/fe/create thread socket
  client/src/page/Channel/ChannelPage.tsx
  client/src/socket.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/thread.saga.ts
  server/src/controller/thread/index.ts
  server/src/controller/thread/thread.controller.ts
  server/src/model/user.model.ts
  server/src/service/thread.service.ts
  server/src/socket.ts
  server/src/swagger/paths/thread-id.yaml
  server/src/swagger/paths/thread.yaml
Labels: Review needed

#147 Feat/fe/redux
  client/src/api/workspace.ts
  client/src/hoc/Auth.tsx
  client/src/store/reducer/workspace.reducer.ts
  client/src/store/saga/workspace.saga.ts
  server/package-lock.json
  server/package.json
Labels: Review needed

#156 Socket Migration to redux
  client/.eslintrc.json
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/socket.ts
  client/src/socket/index.ts
  client/src/store/reducer/index.ts
  client/src/store/reducer/socket.reducer.ts
  client/src/store/saga/channel.saga.ts
  client/src/store/saga/index.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  client/src/store/saga/workspace.saga.ts
  server/src/socket.ts
Labels: FE, Review needed

#157 type 파일 분리, Redux 코드 리펙토링(clean up)
  client/src/component/molecule/Section/index.ts
  client/src/component/organism/ChannelHeader/index.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/SideBar/SideBar.tsx
  client/src/component/organism/ThreadDetail/index.ts
  client/src/component/organism/ThreadList/index.ts
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/page/Workspace/template/Channel.tsx
  client/src/page/WorkspaceBrowser/NewWorkspacePage.tsx
  client/src/page/WorkspaceBrowser/WorkspaceBrowserPage.tsx
  client/src/store/reducer/channel.reducer.ts
  client/src/store/reducer/socket.reducer.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/reducer/workspace.reducer.ts
  client/src/store/saga/channel.saga.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  client/src/store/saga/workspace.saga.ts
  client/src/type/channel.type.ts
  client/src/type/thread.type.ts
  client/src/type/user.type.ts
  client/src/type/workspace.type.ts
  client/tsconfig.json
  client/webpack.config.js
Labels: FE, Review needed

#158 [Sidebar] create modal, fix css
  client/src/component/atom/ModalWrapper/ModalWrapper.tsx
  client/src/component/atom/ModalWrapper/index.ts
  client/src/component/molecule/Section/Section.style.ts
  client/src/component/molecule/Section/Section.tsx
  client/src/component/organism/SideBar/SideBar.tsx
Labels: FE

#159 Thread list 컴포넌트 infinite scroll 적용
  client/src/api/thread.ts
  client/src/component/organism/SideBar/SideBar.tsx
  client/src/component/organism/ThreadList/ThreadList.style.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/page/Workspace/template/Channel.tsx
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/thread.type.ts
  server/src/controller/thread/thread.controller.ts
  server/src/service/thread.service.ts
Labels: BE, FE, Review needed

#166 ChannelInfo Store 변경, get channelInfo API 수정, getUsersByChannel API 구현 중
  client/.eslintrc.json
  client/src/api/user.ts
  client/src/component/molecule/Section/index.ts
  client/src/component/organism/ChannelHeader/ChannelHeader.stories.tsx
  client/src/component/organism/ChannelHeader/ChannelHeader.tsx
  client/src/component/organism/ChannelHeader/index.ts
  client/src/component/organism/MemberListModal/MemberListModal.stories.tsx
  client/src/component/organism/MemberListModal/MemberListModal.tsx
  client/src/component/organism/MemberListModal/index.ts
  client/src/component/organism/SideBar/SideBar.tsx
  client/src/component/organism/ThreadList/index.ts
  client/src/hoc/Auth.tsx
  client/src/page/Workspace/template/Channel.tsx
  client/src/page/Workspace/template/data.ts
  client/src/store/reducer/channel.reducer.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/channel.saga.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/channel.type.ts
  client/src/type/response.type.ts
  client/src/type/thread.type.ts
  server/.eslintrc.json
  server/src/controller/user/index.ts
  server/src/controller/user/user.controller.ts
  server/src/service/channel.service.ts
  server/src/service/user.service.ts
  server/src/swagger/paths/_index.yaml
  server/src/swagger/paths/channel-info.yaml
  server/src/swagger/paths/user-channelId.yaml
Labels: BE, FE, Review needed

#167 workspace관련 page 및 user store 제작 중..
  client/src/api/user.ts
  client/src/api/workspace.ts
  client/src/component/atom/Loading/Loading.tsx
  client/src/component/atom/Loading/index.ts
  client/src/component/atom/index.ts
  client/src/component/organism/WorkspaceCard/WorkspaceCard.tsx
  client/src/component/organism/WorkspaceCard/index.ts
  client/src/component/organism/WorkspaceList/WorkspaceList.style.ts
  client/src/component/organism/WorkspaceList/WorkspaceList.tsx
  client/src/component/organism/WorkspaceList/index.ts
  client/src/component/organism/index.ts
  client/src/constant/color.ts
  client/src/constant/icon.ts
  client/src/hoc/Auth.tsx
  client/src/page/User/LoginPage.tsx
  client/src/page/WorkspaceBrowser/WorkspaceBrowserPage.tsx
  client/src/store/reducer/index.ts
  client/src/store/reducer/user.reducer.ts
  client/src/store/saga/index.ts
  client/src/store/saga/user.saga.ts
  client/src/store/type.ts
  client/src/type/user.type.ts
  client/src/type/workspace.type.ts
  server/@types/user.d.ts
  server/src/controller/user/user.controller.ts
  server/src/middleware/user.middleware.ts
  server/src/service/workspace.service.ts
  server/src/util/jwt.ts
Labels: BE, FE, Review needed

#168 Delete Thread 기능 구현 (#126)
  client/src/api/thread.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/page/Workspace/template/Channel.tsx
  client/src/store/reducer/socket.reducer.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  server/src/service/thread.service.ts
  server/src/socket.ts
Labels: BE, FE, Review needed

#171 Enter key 누르면 thread 생성
  client/src/component/atom/Input/Input.tsx
  client/src/component/atom/Input/index.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
Labels: FE, Review needed

#174 Channel join 기능 구현, Add member modal 구현
  client/src/api/channel.ts
  client/src/api/workspace.ts
  client/src/component/molecule/SelectableTeammate/SelectableTeammate.style.ts
  client/src/component/molecule/SelectableTeammate/SelectableTeammate.tsx
  client/src/component/molecule/SelectableTeammate/index.ts
  client/src/component/molecule/SelectedTeammate/SelectedTeammate.style.ts
  client/src/component/molecule/SelectedTeammate/SelectedTeammate.tsx
  client/src/component/molecule/SelectedTeammate/index.ts
  client/src/component/molecule/index.ts
  client/src/component/organism/AddMemberModal/AddMemberModal.style.ts
  client/src/component/organism/AddMemberModal/AddMemberModal.tsx
  client/src/component/organism/AddMemberModal/index.ts
  client/src/component/organism/ChannelCard/ChannelCard.stories.tsx
  client/src/component/organism/ChannelCard/ChannelCard.tsx
  client/src/component/organism/ChannelCard/index.ts
  client/src/component/organism/ChannelHeader/ChannelHeader.tsx
  client/src/component/organism/ChannelList/ChannelList.style.ts
  client/src/component/organism/ChannelList/ChannelList.tsx
  client/src/component/organism/ChannelList/index.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/component/organism/index.ts
  client/src/page/Workspace/template/ChannelBrowser.tsx
  client/src/store/reducer/channel.reducer.ts
  client/src/store/saga/channel.saga.ts
  client/src/type/channel.type.ts
  server/src/controller/channel/channel.controller.ts
  server/src/controller/channel/index.ts
  server/src/controller/workspace/index.ts
  server/src/controller/workspace/workspace.controller.ts
  server/src/model/index.ts
  server/src/model/userChannelSection.model.ts
  server/src/service/channel.service.ts
  server/src/service/user.service.ts
  server/src/service/workspace.service.ts
Labels: BE, FE, Review needed

#173 Thread의 모든 Message 가져와서 subview (오른쪽 사이드바) 에 렌더링
  client/src/api/message.ts
  client/src/component/organism/ActionBar/ActionBar.tsx
  client/src/component/organism/ActionBar/index.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/ThreadDetail/ThreadDetail.tsx
  client/src/component/organism/ThreadDetail/index.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/component/organism/ThreadList/index.ts
  client/src/type/thread.type.ts
  server/package.json
  server/src/service/message.service.ts
  server/src/swagger/paths/message.yaml
Labels: FE, Review needed

#176 New workspace page, file upload using NCP(s3)
  client/public/index.html
  client/src/api/workspace.ts
  client/src/component/molecule/Section/Section.tsx
  client/src/component/organism/ChannelCard/ChannelCard.tsx
  client/src/component/organism/WorkspaceCard/WorkspaceCard.tsx
  client/src/component/organism/WorkspaceCard/index.ts
  client/src/component/organism/WorkspaceList/WorkspaceList.style.ts
  client/src/component/organism/WorkspaceList/WorkspaceList.tsx
  client/src/hoc/Auth.tsx
  client/src/page/WorkspaceBrowser/NewWorkspacePage.tsx
  client/src/store/saga/user.saga.ts
  client/src/store/saga/workspace.saga.ts
  client/src/type/workspace.type.ts
  client/src/util/myAxios.ts
  server/src/controller/file/file.controller.ts
  server/src/controller/workspace/workspace.controller.ts
  server/src/middleware/file-upload.ts
  server/src/service/channel.service.ts
  server/src/service/workspace.service.ts
Labels: BE, FE, Review needed

#179 Member list modal fix, /user/channel/:channelId api 수정 (searchKeyword 추가)
  client/src/api/channel.ts
  client/src/api/user.ts
  client/src/component/organism/MemberListModal/MemberListModal.style.ts
  client/src/component/organism/MemberListModal/MemberListModal.tsx
  server/src/controller/user/user.controller.ts
  server/src/service/user.service.ts
Labels: BE, FE, Review needed

#180 Message 생성 - 소켓 연결까지 모두 구현 (#36, #124)
  client/src/api/message.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/component/organism/ThreadDetail/ThreadDetail.tsx
  client/src/component/organism/ThreadDetail/index.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/page/WorkspaceBrowser/NewWorkspacePage.tsx
  client/src/store/reducer/socket.reducer.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/message.type.ts
  server/src/controller/message/index.ts
  server/src/controller/message/message.controller.ts
  server/src/service/message.service.ts
  server/src/socket.ts
  server/src/swagger/paths/message-id.yaml
  server/src/swagger/paths/message.yaml
Labels: BE, FE, Review needed

#185 channel member remove / leave channel 기능 구현
  client/src/api/channel.ts
  client/src/component/organism/MemberListModal/MemberListModal.tsx
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/page/Workspace/template/ChannelBrowser.tsx
  client/src/store/reducer/channel.reducer.ts
  client/src/store/reducer/socket.reducer.ts
  client/src/store/saga/channel.saga.ts
  client/src/store/saga/socket.saga.ts
  client/src/type/channel.type.ts
  server/src/controller/channel/channel.controller.ts
  server/src/controller/channel/index.ts
  server/src/service/channel.service.ts
  server/src/socket.ts
Labels: BE, FE, Review needed

#186 delete message 기능 구현 (#182)
  client/src/api/message.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/ThreadDetail/ThreadDetail.tsx
  client/src/store/reducer/socket.reducer.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/message.type.ts
  client/src/type/response.type.ts
  client/src/type/thread.type.ts
  server/src/controller/message/message.controller.ts
  server/src/service/thread.service.ts
  server/src/socket.ts
  server/src/swagger/paths/message-id.yaml
Labels: BE, FE, Review needed

#190 Update message 기능 완성 (#183)
  client/src/api/message.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/store/reducer/socket.reducer.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/message.type.ts
  client/src/type/thread.type.ts
  server/src/socket.ts
Labels: BE, FE, Review needed

#191 Logout, channel 이동시 Thread가 안바뀌는 문제점과 채널 이동시 Thread list 초기화
  client/src/component/organism/Header/Header.tsx
  client/src/hoc/Auth.tsx
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/page/Workspace/template/Channel.tsx
  client/src/store/reducer/thread.reducer.ts
  client/src/store/reducer/user.reducer.ts
  client/src/store/saga/index.ts
  client/src/store/saga/user.saga.ts
  server/src/middleware/user.middleware.ts
Labels: BE, FE

#196 Reaction add/remove 기능 구현(FE/BE 연동)
  client/src/api/reaction.ts
  client/src/component/atom/Button/index.ts
  client/src/component/atom/ModalWrapper/ModalWrapper.tsx
  client/src/component/molecule/ActionMenuButton/ActionMenuButton.tsx
  client/src/component/molecule/ReactionButton/ReactionButton.stories.tsx
  client/src/component/molecule/ReactionButton/ReactionButton.tsx
  client/src/component/molecule/ReactionButton/index.ts
  client/src/component/organism/ActionBar/ActionBar.stories.tsx
  client/src/component/organism/ActionBar/ActionBar.tsx
  client/src/component/organism/ActionBar/index.ts
  client/src/component/organism/MessageActionsMenu/MessageActionsMenu.tsx
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/component/organism/ReactionList/ReactionList.stories.tsx
  client/src/component/organism/ReactionList/ReactionList.tsx
  client/src/component/organism/ReactionList/index.ts
  client/src/component/organism/ReactionPicker/ReactionPicker.stories.tsx
  client/src/component/organism/ReactionPicker/ReactionPicker.tsx
  client/src/component/organism/ReactionPicker/index.ts
  client/src/store/reducer/socket.reducer.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/reaction.type.ts
  client/src/util/calcModalPosition.ts
  server/src/service/reaction.service.ts
  server/src/socket.ts
Labels: BE, FE, Review needed

#195 새로운 thread 생성 또는 내 thread에 reply 생성인 경우 Web Notification (#193)
  client/src/App.tsx
  client/src/constant/index.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/message.type.ts
  server/src/service/message.service.ts
  server/src/socket.ts
Labels: FE, Review needed

#198 Profile modal fix, Modify CSS, MemberListModal의 Add people button 작동하도록 fix 등
  client/src/component/atom/Icon/Icon.tsx
  client/src/component/atom/Icon/index.ts
  client/src/component/atom/Image/index.ts
  client/src/component/atom/Input/Input.tsx
  client/src/component/molecule/ReactionButton/ReactionButton.tsx
  client/src/component/molecule/Section/Section.style.ts
  client/src/component/molecule/Section/Section.tsx
  client/src/component/organism/AddMemberModal/AddMemberModal.tsx
  client/src/component/organism/Avatar/Avatar.tsx
  client/src/component/organism/ChannelHeader/ChannelHeader.tsx
  client/src/component/organism/ChannelList/ChannelList.style.ts
  client/src/component/organism/ChannelList/ChannelList.tsx
  client/src/component/organism/MemberListModal/MemberListModal.tsx
  client/src/component/organism/MessageCard/MessageCard.style.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/component/organism/ReactionList/ReactionList.tsx
  client/src/component/organism/SideBar/SideBar.style.ts
  client/src/component/organism/SideBar/SideBar.tsx
  client/src/component/organism/ThreadList/ThreadList.style.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/component/organism/UserProfileModal/UserProfileModal.tsx
  client/src/component/organism/WorkspaceCard/WorkspaceCard.tsx
  client/src/constant/color.ts
  client/src/page/WorkspaceBrowser/NewWorkspacePage.tsx
  client/src/page/WorkspaceBrowser/WorkspaceBrowserPage.tsx
  client/src/util/calcModalPosition.ts
Labels: FE, Review needed

#200 channel browse 쿼리 수정, ChannelCard link를 위한 workspaceId 수정
  client/src/component/organism/ChannelCard/ChannelCard.tsx
  server/src/service/channel.service.ts
Labels: BE, FE, Review needed

#202 Notification 발생 시 Sidebar Bold 처리 (#194)
  client/src/App.tsx
  client/src/component/molecule/ReplyButton/ReplyButton.tsx
  client/src/component/molecule/Section/Section.tsx
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/store/reducer/channel.reducer.ts
  client/src/store/reducer/socket.reducer.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/channel.type.ts
  server/src/service/thread.service.ts
Labels: FE, Review needed

#201 Channel page의 Header 및 thread list top에서 DM 구분
  client/src/component/organism/AddMemberModal/AddMemberModal.tsx
  client/src/component/organism/ChannelHeader/ChannelHeader.style.ts
  client/src/component/organism/ChannelHeader/ChannelHeader.tsx
  client/src/component/organism/MemberListModal/MemberListModal.tsx
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/util/getDMChannelTitle.ts
Labels: FE, Review needed

#205 People page subview 구현
  client/src/component/organism/TeammateList/TeammateList.style.ts
  client/src/component/organism/TeammateList/TeammateList.tsx
  client/src/component/organism/TeammateList/index.ts
  client/src/component/organism/UserDetail/UserDetail.style.ts
  client/src/component/organism/UserDetail/UserDetail.tsx
  client/src/component/organism/UserDetail/index.ts
  client/src/component/organism/index.ts
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/page/Workspace/template/People.tsx
Labels: FE, Review needed

#206 Add images to reply button
  client/src/component/molecule/ReplyButton/ReplyButton.stories.tsx
  client/src/component/molecule/ReplyButton/ReplyButton.style.ts
  client/src/component/molecule/ReplyButton/ReplyButton.tsx
  client/src/component/molecule/ReplyButton/index.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
Labels: FE, Review needed

#207 Feat/web/socket
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/store/reducer/socket.reducer.ts
  client/src/store/reducer/workspace.reducer.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/workspace.saga.ts
  client/src/type/workspace.type.ts
  server/src/socket.ts
Labels: BE, FE, Review needed

#209 workspace join page logic 수정
  client/src/App.tsx
  client/src/api/workspace.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/component/organism/SideBar/SideBar.tsx
  client/src/page/WorkspaceBrowser/WorkspaceBrowserPage.tsx
  client/src/page/WorkspaceBrowser/WorkspaceJoinPage.tsx
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/workspace.saga.ts
  server/src/socket.ts
Labels: FE, Review needed

#211 채널 가져온 뒤 소켓 연결하도록 변경
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/channel.saga.ts
  client/src/store/saga/socket.saga.ts
  client/src/type/channel.type.ts
  server/src/socket.ts
Labels: FE, Review needed

#215 Channel browser page - 채널 검색 기능 구현
  client/src/api/channel.ts
  client/src/component/organism/ChannelList/ChannelList.style.ts
  client/src/component/organism/ChannelList/ChannelList.tsx
  client/src/component/organism/ChannelList/index.ts
  client/src/component/organism/TeammateList/index.ts
  client/src/page/Workspace/template/ChannelBrowser.tsx
  client/src/page/Workspace/template/People.tsx
  client/src/type/channel.type.ts
  server/src/controller/channel/channel.controller.ts
  server/src/service/channel.service.ts
Labels: BE, FE, Review needed

#216 socket connect연결 순서 및 workspace join시 해당 워크스페이스로 + html favicon
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/page/WorkspaceBrowser/NewWorkspacePage.tsx
  client/src/page/WorkspaceBrowser/WorkspaceBrowserPage.tsx
  client/src/page/WorkspaceBrowser/WorkspaceJoinPage.tsx
  client/src/store/saga/channel.saga.ts
  client/src/store/saga/socket.saga.ts
  client/webpack.config.js
  server/src/socket.ts
Labels: BE, FE, Review needed

#219 Socket 통신 에러 해결 (#214)
  client/src/api/thread.ts
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/thread.saga.ts
  client/src/type/thread.type.ts
  server/src/socket.ts
Labels: BE, FE

#222 Channel browser의 Join/Leave 기능 fix
  client/src/api/channel.ts
  client/src/component/organism/ChannelCard/ChannelCard.tsx
  client/src/page/Workspace/template/ChannelBrowser.tsx
  client/src/store/reducer/channel.reducer.ts
  client/src/store/reducer/socket.reducer.ts
  client/src/store/saga/channel.saga.ts
  client/src/store/saga/socket.saga.ts
  client/src/type/channel.type.ts
  server/src/socket.ts
Labels: BE, FE, Review needed

#227 Reaction subview rendering fix, BE db check before create new reaction
  client/src/store/reducer/thread.reducer.ts
  client/src/type/reaction.type.ts
  server/src/service/reaction.service.ts
Labels: BE, FE, Review needed

#231 Channel page - join 되지 않은 public channel 접근 시 렌더링 변경
  client/src/component/organism/ThreadDetail/ThreadDetail.style.ts
  client/src/component/organism/ThreadDetail/ThreadDetail.tsx
  client/src/component/organism/ThreadDetail/index.ts
  client/src/component/organism/ThreadList/ThreadList.style.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/type/channel.type.ts
Labels: FE, Review needed

#234 fix datetime convert error
  client/src/component/organism/DmCard/DmCard.tsx
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/util/date.ts
Labels: FE, Review needed

#236 Sidebar - workspace list 추가
  client/src/component/organism/SideBar/SideBar.style.ts
  client/src/component/organism/SideBar/SideBar.tsx
  client/src/component/organism/WorkspaceSideBar/WorkspaceSideBar.style.ts
  client/src/component/organism/WorkspaceSideBar/WorkspaceSideBar.tsx
  client/src/component/organism/WorkspaceSideBar/index.ts
  client/src/component/organism/index.ts
  client/src/page/Workspace/WorkspacePage.tsx
Labels: FE, Review needed

#237 Refactor modal style, add key props on list
  client/src/component/molecule/Section/Section.tsx
  client/src/component/molecule/SendEmailModal/SendEmailModal.tsx
  client/src/component/organism/Header/Header.tsx
  client/src/component/organism/TeammateList/TeammateList.tsx
  client/src/component/organism/WorkspaceSideBar/WorkspaceSideBar.tsx
Labels: FE, Review needed

#238 remove any type from Input props
  client/src/component/atom/Input/index.ts
  client/src/component/organism/DmCard/index.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/type/channel.type.ts
Labels: FE, Review needed

#239 Add home button in WorkspaceSideBar
  client/src/component/organism/WorkspaceSideBar/WorkspaceSideBar.tsx
  client/src/constant/icon.ts
Labels: FE, Review needed

#242 style - css 수정
  client/src/component/atom/Button/Button.tsx
  client/src/component/molecule/ActionMenuButton/ActionMenuButton.tsx
  client/src/component/molecule/Modal/Modal.tsx
  client/src/component/molecule/Section/Section.style.ts
  client/src/component/molecule/Section/Section.tsx
  client/src/component/organism/Header/Header.tsx
  client/src/component/organism/MessageActionsMenu/MessageActionsMenu.tsx
  client/src/component/organism/WorkspaceSideBar/WorkspaceSideBar.tsx
Labels: FE, Review needed

#245 Channel 접근 가능 여부 API
  client/src/api/channel.ts
  client/src/hoc/PrivateChannelRoute.tsx
  client/src/page/Workspace/WorkspacePage.tsx
  client/src/type/channel.type.ts
  server/src/controller/channel/channel.controller.ts
  server/src/controller/channel/index.ts
  server/src/service/channel.service.ts
  server/src/swagger/paths/_index.yaml
  server/src/swagger/paths/channel-joined.yaml
Labels: BE, FE

#246 Fix storybook path alias configure
  client/.storybook/main.js
  client/src/component/organism/MessageCard/MessageCard.stories.tsx
Labels: FE, Review needed

#250 People page layout 변경, Invite people 버튼 고정, SendEmailModal css 수정
  client/src/component/molecule/SendEmailModal/SendEmailModal.style.ts
  client/src/component/molecule/SendEmailModal/SendEmailModal.tsx
  client/src/component/organism/TeammateCard/TeammateCard.style.ts
  client/src/component/organism/TeammateCard/TeammateCard.tsx
  client/src/component/organism/TeammateCard/index.ts
  client/src/component/organism/TeammateList/TeammateList.style.ts
  client/src/component/organism/TeammateList/TeammateList.tsx
Labels: FE, Review needed

#251 Display Threads divided by day, Show created time when hover continuous Thread
  client/src/component/molecule/DayDivider/DayDivider.style.ts
  client/src/component/molecule/DayDivider/DayDivider.tsx
  client/src/component/molecule/DayDivider/index.ts
  client/src/component/molecule/index.ts
  client/src/component/organism/MessageCard/MessageCard.style.ts
  client/src/component/organism/MessageCard/MessageCard.tsx
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/util/date.ts
Labels: FE, Review needed

#255 Add member 후처리(소켓 연결), Scroll/Button 등 css 수정
  client/src/component/atom/Button/Button.tsx
  client/src/component/atom/Icon/Icon.tsx
  client/src/component/molecule/DayDivider/DayDivider.style.ts
  client/src/component/organism/AddMemberModal/AddMemberModal.style.ts
  client/src/component/organism/AddMemberModal/AddMemberModal.tsx
  client/src/component/organism/ChannelBrowserHeader/ChannelBrowserHeader.tsx
  client/src/component/organism/ChannelList/ChannelList.style.ts
  client/src/component/organism/MessageEditor/MessageEditor.tsx
  client/src/component/organism/SideBar/SideBar.style.ts
  client/src/component/organism/TeammateList/TeammateList.style.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/component/organism/WorkspaceSideBar/WorkspaceSideBar.style.ts
  client/src/store/reducer/channel.reducer.ts
  client/src/store/reducer/socket.reducer.ts
  client/src/store/saga/channel.saga.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/thread.saga.ts
  server/src/socket.ts
Labels: BE, FE, Review needed

#258 Sidebar channel name ellipsis, modify css
  client/src/component/molecule/Section/Section.style.ts
  client/src/component/molecule/Section/Section.tsx
  client/src/component/organism/DmCard/DmCard.style.ts
  client/src/component/organism/DmCard/DmCard.tsx
  client/src/constant/color.ts
Labels: FE, Review needed

#260 NotFoundPage 수정
  client/src/constant/icon.ts
  client/src/page/NotFoundPage.tsx
  client/src/page/Workspace/WorkspacePage.tsx
Labels: FE, Review needed

#261 User profile의 Message button 기능 활성화
  client/src/component/organism/Avatar/Avatar.tsx
  client/src/component/organism/UserDetail/UserDetail.tsx
  client/src/store/saga/channel.saga.ts
  server/src/service/channel.service.ts
Labels: BE, FE, Review needed

#263 Remove member 후 모달 상태 변화 반영
  client/src/component/organism/MemberListModal/MemberListModal.tsx
  client/src/store/reducer/channel.reducer.ts
  client/src/store/saga/channel.saga.ts
Labels: FE, Review needed

#265 Notification 메시지/스레드 생성한 사람 이름으로 오게 수정
  client/src/store/saga/thread.saga.ts
Labels: FE

#266 Refactor Infinite scroll in thread list
  client/src/component/organism/ThreadList/ThreadList.style.ts
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/store/reducer/thread.reducer.ts
  client/src/util/throttling.ts
Labels: FE, Review needed

#267 Reaction tooltip 구현
  client/src/component/molecule/ReactionButton/ReactionButton.style.ts
  client/src/component/molecule/ReactionButton/ReactionButton.tsx
  client/src/component/molecule/Tooltip/Tooltip.style.ts
  client/src/component/molecule/Tooltip/Tooltip.tsx
  client/src/component/molecule/Tooltip/index.ts
  client/src/component/molecule/index.ts
  client/src/component/organism/ReactionList/ReactionList.tsx
  client/src/component/organism/ReactionList/index.ts
Labels: FE, Review needed

#268 Fix Infinite scroll in Thread list
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/store/reducer/thread.reducer.ts
Labels: FE, Review needed

#269 Add color props to Loading component, Use Loading atom in ThreadList
  client/src/component/atom/Loading/Loading.tsx
  client/src/component/organism/ThreadList/ThreadList.tsx
  client/src/hoc/Auth.tsx
  client/src/hoc/PrivateWorkspace.tsx
  client/src/page/WorkspaceBrowser/WorkspaceBrowserPage.tsx
Labels: FE, Review needed

#271 update thread시 subview에도 반영
  client/src/page/WorkspaceBrowser/NewWorkspacePage.tsx
  client/src/store/reducer/thread.reducer.ts
  client/src/store/saga/socket.saga.ts
  client/src/store/saga/workspace.saga.ts
Labels: FE, 버그수정

#272 Fixed Section channel name scroll
  client/src/component/molecule/Section/Section.style.ts
Labels: FE, Review needed

#280 Fixed all dms page search function
  client/src/page/Workspace/template/AllDms.tsx
Labels: FE, Review needed

#282 Notification에 채널 이름 추가
  client/src/store/saga/thread.saga.ts
Labels: FE

#284 Fix Hoc error, Change Notification Content
  client/src/hoc/Auth.tsx
  client/src/store/saga/thread.saga.ts
  server/src/controller/user/index.ts
  server/src/controller/user/user.controller.ts
  server/src/middleware/user.middleware.ts
Labels: BE, FE
